# Generated by Django 3.2.5 on 2021-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Link', models.URLField(blank=True, max_length=400)),
                ('Icon', models.ImageField(upload_to='Social_icon/')),
                ('Website_name', models.CharField(max_length=30)),
            ],
        ),
    ]
