# Generated by Django 3.2.5 on 2021-07-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top_bar',
            new_name='Index_Top_bar',
        ),
    ]
