# Generated by Django 3.2.5 on 2021-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_top_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Background_image', models.ImageField(upload_to='Home_page_top_bar/')),
                ('Title', models.CharField(max_length=50)),
                ('Sub_title', models.CharField(max_length=100)),
                ('Link', models.URLField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Name', models.CharField(max_length=50)),
                ('Blog_title', models.CharField(max_length=100)),
                ('Sub_title', models.CharField(blank=True, max_length=200)),
                ('Description', models.CharField(max_length=1000)),
                ('Image', models.ImageField(blank=True, upload_to='Blog_images/')),
            ],
        ),
    ]
