# Generated by Django 3.2.5 on 2021-07-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_sections',
            new_name='Post_Blog_sections',
        ),
        migrations.RenameModel(
            old_name='About_top_bar',
            new_name='Post_top_bar',
        ),
    ]
